//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessGame.NativeApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChessGameNativeAppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChessGameNativeAppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessGame.NativeApp.ChessGameNativeAppRes", typeof(ChessGameNativeAppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte účet?.
        /// </summary>
        internal static string BasicAuthView_BasicAuthAccountQuestion {
            get {
                return ResourceManager.GetString("BasicAuthView_BasicAuthAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        internal static string BasicAuthView_Caption {
            get {
                return ResourceManager.GetString("BasicAuthView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string BasicAuthView_EmailLabel {
            get {
                return ResourceManager.GetString("BasicAuthView_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací email.
        /// </summary>
        internal static string BasicAuthView_EmailPlaceholder {
            get {
                return ResourceManager.GetString("BasicAuthView_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příhlásit se.
        /// </summary>
        internal static string BasicAuthView_LoginButtonTitle {
            get {
                return ResourceManager.GetString("BasicAuthView_LoginButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string BasicAuthView_PasswordLabel {
            get {
                return ResourceManager.GetString("BasicAuthView_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte heslo.
        /// </summary>
        internal static string BasicAuthView_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("BasicAuthView_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaregistrujte se.
        /// </summary>
        internal static string BasicAuthView_RegistrationReferenceTitle {
            get {
                return ResourceManager.GetString("BasicAuthView_RegistrationReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/Black_Bishop.svg.
        /// </summary>
        internal static string ChessPieceImg_BlackBishop {
            get {
                return ResourceManager.GetString("ChessPieceImg_BlackBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/Black_King.svg.
        /// </summary>
        internal static string ChessPieceImg_BlackKing {
            get {
                return ResourceManager.GetString("ChessPieceImg_BlackKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/Black_Knight.svg.
        /// </summary>
        internal static string ChessPieceImg_BlackKnight {
            get {
                return ResourceManager.GetString("ChessPieceImg_BlackKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/Black_Pawn.svg.
        /// </summary>
        internal static string ChessPieceImg_BlackPawn {
            get {
                return ResourceManager.GetString("ChessPieceImg_BlackPawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/Black_Queen.svg.
        /// </summary>
        internal static string ChessPieceImg_BlackQueen {
            get {
                return ResourceManager.GetString("ChessPieceImg_BlackQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/Black_Rook.svg.
        /// </summary>
        internal static string ChessPieceImg_BlackRook {
            get {
                return ResourceManager.GetString("ChessPieceImg_BlackRook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/White_Bishop.svg.
        /// </summary>
        internal static string ChessPieceImg_WhiteBishop {
            get {
                return ResourceManager.GetString("ChessPieceImg_WhiteBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/White_King.svg.
        /// </summary>
        internal static string ChessPieceImg_WhiteKing {
            get {
                return ResourceManager.GetString("ChessPieceImg_WhiteKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/White_Knight.svg.
        /// </summary>
        internal static string ChessPieceImg_WhiteKnight {
            get {
                return ResourceManager.GetString("ChessPieceImg_WhiteKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/White_Pawn.svg.
        /// </summary>
        internal static string ChessPieceImg_WhitePawn {
            get {
                return ResourceManager.GetString("ChessPieceImg_WhitePawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/White_Queen.svg.
        /// </summary>
        internal static string ChessPieceImg_WhiteQueen {
            get {
                return ResourceManager.GetString("ChessPieceImg_WhiteQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/chessPieces/White_Rook.svg.
        /// </summary>
        internal static string ChessPieceImg_WhiteRook {
            get {
                return ResourceManager.GetString("ChessPieceImg_WhiteRook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrát sám se sebou.
        /// </summary>
        internal static string GameplayPage_PlayAloneButtonTitle {
            get {
                return ResourceManager.GetString("GameplayPage_PlayAloneButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítej.
        /// </summary>
        internal static string MainLayout_Greetings {
            get {
                return ResourceManager.GetString("MainLayout_Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string MainLayout_Logout {
            get {
                return ResourceManager.GetString("MainLayout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        internal static string ModalManager_CloseButtonTitle {
            get {
                return ResourceManager.GetString("ModalManager_CloseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrát.
        /// </summary>
        internal static string NavMenu_GamesTitle {
            get {
                return ResourceManager.GetString("NavMenu_GamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoce.
        /// </summary>
        internal static string PromotionModal_Title {
            get {
                return ResourceManager.GetString("PromotionModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace.
        /// </summary>
        internal static string RegistrationView_Caption {
            get {
                return ResourceManager.GetString("RegistrationView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte už účet?.
        /// </summary>
        internal static string RegistrationView_DoYouHaveAccount {
            get {
                return ResourceManager.GetString("RegistrationView_DoYouHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegistrationView_EmailLabel {
            get {
                return ResourceManager.GetString("RegistrationView_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací email.
        /// </summary>
        internal static string RegistrationView_EmailPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationView_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašte se.
        /// </summary>
        internal static string RegistrationView_LoginReferenceTitle {
            get {
                return ResourceManager.GetString("RegistrationView_LoginReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přezdívka.
        /// </summary>
        internal static string RegistrationView_NicknameLabel {
            get {
                return ResourceManager.GetString("RegistrationView_NicknameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte přezdívku.
        /// </summary>
        internal static string RegistrationView_NicknamePlaceholder {
            get {
                return ResourceManager.GetString("RegistrationView_NicknamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla se neshodují.
        /// </summary>
        internal static string RegistrationView_PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("RegistrationView_PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        internal static string RegistrationView_PasswordLabel {
            get {
                return ResourceManager.GetString("RegistrationView_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte heslo.
        /// </summary>
        internal static string RegistrationView_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationView_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaregistrovat se.
        /// </summary>
        internal static string RegistrationView_RegistrationButtonLabel {
            get {
                return ResourceManager.GetString("RegistrationView_RegistrationButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ověření hesla.
        /// </summary>
        internal static string RegistrationView_RepeatPasswordLabel {
            get {
                return ResourceManager.GetString("RegistrationView_RepeatPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zopakujte heslo.
        /// </summary>
        internal static string RegistrationView_RepeatPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationView_RepeatPasswordPlaceholder", resourceCulture);
            }
        }
    }
}
